language: python
python: "3.4"
sudo: false
before_install: pip install -r requirements.txt
before_script:
  - mkdir pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - python scripts/split_corpus.py -l pickle
  - python setup.py install
  - python -m nltk.downloader averaged_perceptron_tagger punkt
env:
  - TEST_SUITE=unit
  - TEST_SUITE=parse_all
  - TEST_SUITE=convert_all
  - TEST_SUITE=convert_all_sentences
script: ci/test.sh

